#!/bin/bash


#accessing by variable index


beatles=( John Paul Ringo George )

#set index to be index[0-3] essentially
for index in $(seq 0 $((${#beatles[@]} - 1)));do
	echo "Beatle $index is ${beatles[$index]}";done

echo now again with the fifth beatle

beatles[5]=Stuart
for index in $(seq 0 $((${#beatles[@]} - 1)));do
	echo Beatle $index is ${beatles[$index]};done

echo "Missed it; beatle 5 is ${beatles[5]}"
