#!/bin/bash

#can do some simple math with the [] brackets in arrays

function bubblesort(){

n=${#data[@]}
for i in `seq 0 $n`;do
	for (( j=n; j >i; j-=1 ));do
		if [[ ${data[j-1]} > ${data[j]} ]];then
		temp=${data[j]}
		data[j]=${data[j-1]}
		data[j-1]=$temp;fi
	done
done

}


data=( roger oscar charlie kilo indigo tango )
echo "initial Stage"
echo
for i in ${data[@]};do
echo "$i";done
echo
bubblesort
echo
echo Final stage:
echo
for i in ${data[@]};do
	echo $i;done

