#!/bin/bash


getipaddr() {

cd /etc/sysconfig/network-scripts || return 1

if [ -f ifcfg-$1 ];then
	unset IPADDR
	. ifcfg-$1
if [ -z "$IPADDR" ];then
	return 2;else
	echo $IPADDR;fi;else
	return 3;fi
	return 0 #not strictly needed

}

for thisnic in eth0 eth1 eth2;do
	thisnip=`getipaddr $thisnic`
	case $? in
		0) echo "The IP Address configured for $thisnic is $thisip" ;;
		1) echo "This does not seem to be a Redhat system" ;;
		2) echo "No IP Address defined for $thisnic" ;;
		3) echo "No configuration file found for $thisnic" ;;
	esac
done
